### ISSUE TITLE
No checks for python version result in unhelpful error messages

### ISSUE THREAD

**Issue by brhillman** [ESCOMP/CESM_CICE5#10]
It appears that cice is incompatible with Python 3.x, but there are not any checks for Python version in use. This can lead to some misleading and unhelpful error messages when the wrong version of Python (i.e., 3.x) is accidentally used. In my case, I need to explicitly load the proper Python module before trying to use any of the CIME build and run scripts, or I run into some misleading errors. For example, if I try to run `case.build` without first loading the Python 2.7.9 module in my environment, I get the following error:
```
ERROR: Command: './generate_cice_decomp.pl -ccsmroot /home/bhillma/codes/e3sm/branches/add-rrtmgp -res ne4np4 -nx 866 -n
y 1 -nproc 16.0 -thrds 1 -output all' failed with error 'b'Value "16.0" invalid for option nproc (number expected)\nSYNO
PSIS\n     generate_cice_decomp.pl [options]\nOPTIONS\n     -ccsmroot <path>               Full pathname for ccsmroot\n 
                                   (required)\n     -nproc <number>      (or -n)   Number of mpi tasks used.\t\n        
                            (required)\n     -nx <number>                   number of lons \n                           
         (optional, default is 320)\n     -ny <number>                   number of lats\n                               
     (optional, default is 384)\n     -res <resolution>    (or -r)   Horizontal resolution \n                           
         (optional, default gx1v6)\n     -thrds <number>      (or -t)   Number of threads per mpi task\n                
                    (optional, default 1)\n     -output <type>\t  (or -o)   Either output: all, maxblocks, bsize-x, bsiz
e-y, or decomptype\n\t\t\t            (optional, default all)\n\nEXAMPLES\n\n   generate_cice_decomp.pl -res gx1v6 -nx 3
20 -ny 384  -nproc 80 -output maxblocks\n\n   will return a single value -- t
```
The actual error is that things seem to be parsed differently here in Python 2 vs Python 3, but it would be most useful to have a check at the beginning that made sure the user was invoking the script with the correct Python version if the code requires that.

**Comment by dabail10** [comment]
Thanks @brhillman. Sorry I missed this until now. We recently made sure the CIME scripts were compatible with both Python 3 and 2. However, I will look into this further.

**Comment by brhillman** [comment]
@dabail10 no problem. It's been a minor annoyance. It looks like this is because different versions of Python are handling `ntasks = ntasks_ice / ninst_ice` in the `buildnml` script as either integer or floating point division. A simple fix (via Matt Norman) would be to change this line to `ntasks = int(ntasks_ice / ninst_ice)`. I was going to open up a PR on our (E3SM) end to fix this, but it looks like this is handled differently in the repo here. So, maybe this isn't relevant to you all.

**Comment by dabail10** [comment]
That is similar to the fix that went in on April 17th. I will add this here. So, are you using CESM_CICE5 as your wrapper to MPAS-ice?

https://github.com/ESCOMP/CESM_CICE5/commit/7de758141b51b297081c26a0ce1758de100b9e20

**Comment by dabail10** [comment]
In the latest version of our CIME wrapper, we now get ninst from CIME. We removed this calculation here.

**Comment by brhillman** [comment]
@dabail10 to be honest, I don't know, this is well outside of stuff I usually look at. It looks to me though like this issue is not relevant to the version of the code here, so I am going to close this issue and reopen on the E3SM end. I imagine this will be fixed next time we merge changes from here, but I'm definitely not the point of contact for that.
