### ISSUE TITLE
potential OMP issue in subroutine ocn_data_hadgem of ice_forcing.F90

### ISSUE THREAD

**Issue by klindsay28** [ESCOMP/CESM_CICE5#7]
It looks like `workx` and `worky` should be included in the OMP private declaration in the following block from subroutine ocn_data_hdgem of src/source/ice_forcing.F90 (which I don't know if anyone is actively using):

         !$OMP PARALLEL DO PRIVATE(iblk,i,j)
         do iblk = 1, nblocks
            do j = 1, ny_block
            do i = 1, nx_block

               workx      = uocn(i,j,iblk) 
               worky      = vocn(i,j,iblk)
               uocn(i,j,iblk) = workx*cos(ANGLET(i,j,iblk)) & 
                                  + worky*sin(ANGLET(i,j,iblk))   
               vocn(i,j,iblk) = worky*cos(ANGLET(i,j,iblk)) & 
                                  - workx*sin(ANGLET(i,j,iblk))

               uocn(i,j,iblk) = uocn(i,j,iblk) * cm_to_m
               vocn(i,j,iblk) = vocn(i,j,iblk) * cm_to_m

            enddo		! i
            enddo		! j
         enddo		! nblocks
         !$OMP END PARALLEL DO

**Comment by dabail10** [comment]
Not sure why I was not notified of this. Within the CESM, we do not use ice_forcing.F90 at all. However, this should go back into the CICE Consortium version. Good catch Keith.
